name: safety_zone
description: "Safety Zone."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  connectivity_plus: ^5.0.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.8
  get_it: ^8.0.3
  intl: ^0.18.1
  image_picker: ^1.0.7
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  retrofit: ^4.0.1
  shared_preferences: ^2.5.2
  chucker_flutter:
  flutter_map: ^6.1.0
  geolocator:
  geocoding:
  pin_code_fields: ^8.0.1
  skeletonizer: ^1.4.3
  google_maps_flutter: ^2.12.3
  photo_view:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications: ^19.3.0
  rxdart:
  huawei_hmsavailability: ^6.12.0+300
  firebase_crashlytics: ^4.3.9
  file_picker:
  flutter_spinkit:



dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  retrofit_generator: ^7.0.1
  build_runner: ^2.3.3
  device_info_plus:
  intl_utils:  ^2.8.8


dependency_overrides:
  intl: ^0.20.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_intl:
  enabled: true